### ISSUE TITLE
File littlesis_developemnt_db.sql.gz is missing

### ISSUE THREAD

**Issue by goldleader** [public-accountability/littlesis-main#36]
File littlesis_developemnt_db.sql.gz is missing in the repository, so Step #6 in the installation instructions fails:  zcat littlesis_developemnt_db.sql.gz | littlesis psql

The install process completes successfully otherwise.

**Comment by aepyornis** [comment]
hey @goldleader, instead of what's listed in step #6 try running `./littlesis rake db:setup`

**Comment by goldleader** [comment]
Yes that works. Thanks.
